before_script:
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

rake:
  script:
    - bundle exec rake

rubocop:
  script:
    - rubocop

brakeman:
  script:
    - bundle exec rake brakeman
