before_script:
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"
  - bundle exec rake db:create
  - bundle exec rake db:migrate:reset

rake:
  script:
    - bundle exec rake

rubocop:
  script:
    - bundle exec rubocop

brakeman:
  script:
    - bundle exec rake brakeman
