AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/*
    - config/**/*

Rails:
  Enabled: true

Rails/TimeZone:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/ClassLength:
  Max: 4000
  CountComments: false

Metrics/MethodLength:
  Max: 400
  CountComments: false

Metrics/AbcSize:
  Max: 100

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20

Style/IfUnlessModifier:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/WordArray:
  Enabled: false