AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/*
    - config/**/*

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/ClassLength:
  Max: 4000
  CountComments: false
  
Metrics/MethodLength:
  Max: 400
  CountComments: false