language: ruby
rvm:
  - "2.3.4"
  - "2.4.0"
services: postgresql
bundler_args: --without test development
before_script:
  - psql -c 'create database nightingale_test;' -U postgres
script:
  - bundle exec bundle-audit check --update
  - bundle exec brakeman -qAzw1
  - bundle exec rake
