language: ruby
rvm:
  - "2.3.4"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
services: postgresql
bundler_args: --without test development
script:
  - bundle exec bundle-audit check --update
  - bundle exec brakeman -qAzw1
  - export DISPLAY=:99.0 && bundle exec rake
