language: ruby
rvm:
  - "2.3.4"
  - "2.4.0"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
services: postgresql
bundler_args: --without test development
before_script:
  - psql -c 'create database nightingale_test;' -U postgres
script:
  - bundle exec bundle-audit check --update
  - bundle exec brakeman -qAzw1
  - export DISPLAY=:99.0 && bundle exec rake
