defaults:  &defaults
  funeral_director:
    - 'identity'
    - 'demographics'
    - 'disposition'
    - 'send_to_medical_professional'
    - 'medical'
    - 'send_to_registrar'

  physician:
    - 'medical'
    - 'send_to_funeral_director'
    - 'identity'
    - 'demographics'
    - 'disposition'
    - 'send_to_registrar'

  other:
    - 'identity'
    - 'demographics'
    - 'disposition'
    - 'medical'
    - 'send_to_registrar'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults